@startuml horusec-operator-c3
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Deployment.puml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Dynamic.puml

LAYOUT_WITH_LEGEND()
LAYOUT_LEFT_RIGHT()

Person(user, "SRE/DevSecOps/DevOps", "User who wants to install or maintain Horusec-Platform in a Kubernetes cluster")

System_Boundary(horusecOperator, "Horusec-Operator") {
  System(HorusecOperatorPhase0, "User installs Horusec CRD in their cluster")
  System(HorusecOperatorPhase1, "Kubernetes informs Horusec-operator that there was an external change in Horusec's resources")
  System(HorusecOperatorPhase2, "When notified by Kubernetes, Horusec-Operator searches for the altered definitions.")
  System(HorusecOperatorPhase3, "Horusec-Operator compares the definitions with the current installation")
  System(HorusecOperatorPhase4, "It applies the settings state to achieve the desired state")
}

System_Ext(Kubernetes, "Kubernetes", "Container orchestration system")

Rel(user, HorusecOperatorPhase0, "")
Rel(HorusecOperatorPhase0, Kubernetes, "")
Rel(Kubernetes, HorusecOperatorPhase1, "")
Rel(HorusecOperatorPhase1, HorusecOperatorPhase2, "")
Rel(HorusecOperatorPhase2, HorusecOperatorPhase3, "")
Rel(HorusecOperatorPhase3, HorusecOperatorPhase4, "")

@enduml