@startuml horusec-platform-c2
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Deployment.puml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Dynamic.puml

LAYOUT_WITH_LEGEND()

Person(developer, "Membro (Desenvolvedor/QA)", "Usuário básico do Horusec, possui apenas permissão de leitura sobre workspace ou repositório.")
Person(supervisor, "Supervisor (AppSec/TechLead)", "Usuário com permissão especifica para repositórios, consegue realizar a gestão de vulnerabilidades e operações de leitura.")
Person(admin, "Administrador (PO/Head)", "Usuário com o maior nível de permissões do Horusec, possui todas as permissões de escrita e leitura.")
Person(applicationAdmin, "Administrador da Aplicação (CTO/Principal)", "Usuário opcional especial que possui todas as permissões do administrador, caso ativado apenas ele conseguirá criar novos workspaces, removendo essa permissão do administrador padrão.")

System_Boundary(horusecPlatform, "Horusec Platform") {
  System(HorusecManager, "Horusec-Manager", "Aplicação com a interface gráfica web do Horusec")
  System(HorusecAuth, "Horusec-Auth", "Serviço de autorização e autenticação.")
  System(HorusecCore, "Horusec-Core", "Serviço de gestão de entidades: Workspace, Repositórios e Usuários.")
  System(HorusecVulnerability, "Horusec-Vulnerability", "Serviço de gestão da entidade: Vulnerabilidade(salvar, buscar e atualizar no banco de dados)")
  System(HorusecWebhook, "Horusec-Webhook", "Serviço de gestão da entidade: Webhook; Serviço de integração para terceiros através de gatilhos.")
  System(HorusecAnalytic, "Horusec-Analytic", "Serviço de gestão do dashboard para as entidades: Vulnerabilidades por autor, Vulnerabilidades por tempo, Vulnerabilidades por linguagem, Vulnerabilidades por repositório")
  System(HorusecAPI, "Horusec-API", "Serviço de gestão das análises recebidas pela Horusec-CLI. Seu objetivo é receber a análise realizada e salvar em sua base de dados.")
  System(HorusecMessages, "Horusec-Messages", "Serviço de envio de email")

  Container(HorusecMigrations, "Horusec-Migrations", "Job Service", "Serviço de migração e atualização das tabelas do banco de dados")

  ContainerDb(HorusecPlatformDatabase, "Database-Platform", "(Postgresql:12)", "Armazena nova análise no banco de dados platform")
  ContainerDb(HorusecAnalyticDatabase, "Database-Analytic", "(Postgresql:12)", "Armazena dados do dashboard")
}

System_Ext(horusecCLI, "Horusec CLI", "Interface de linha de comandos do Horusec, realiza análise estática de código em busca de vulnerabilidades.")
System_Ext(externalAPP, "Aplicação Externa", "Aplicação externa que irá receber os dados da análise do Horusec.")

Rel(developer, HorusecManager, "Busca worksapaces e repositórios, visualiza vulnerabilidades e dashboard dos repositórios ao qual tem permissão.")
Rel(supervisor, HorusecManager, "Busca worksapaces e repositórios, gestão de vulnerabilidades e dashboard dos repositórios ao qual tem permissão.")
Rel(admin, HorusecManager, "Permissão de escrita em workspaces e repositórios, criação de tokens, gestão de vulnerabilidades, dashboard de workspace e repositórios.")
Rel(applicationAdmin, HorusecManager, "Permissão de escrita em workspaces e repositórios, criação de tokens, gestão de vulnerabilidades, dashboard de workspace e repositórios.")


Rel(HorusecManager, HorusecAuth, "Realizar Login; Cadastro de usuário; Recuperação de senha; Renovação de token de sessão.")
Rel(HorusecManager, HorusecCore, "Criar, Atualizar, Deletar, Visualizar workspace; Gestão de acessos ao workspace; Adicionar, Deletar, Visualizar Tokens de workspace; Criar, Atualizar, Deletar, Visualizar repositório; Gestão de acessos ao repositório; Adicionar, Deletar, Visualizar Tokens de repositório.")
Rel(HorusecManager, HorusecVulnerability, "Visualiza vulnerabilidades por repositório; Atualiza severidade e tipo da vulnerabilidade.")
Rel(HorusecManager, HorusecWebhook, "Criar, Atualizar, Deletar, Visualizar webhook do repositório.")
Rel(HorusecManager, HorusecAnalytic, "Visualizar dados analíticos das análises")

Rel(HorusecAuth, HorusecMessages, "Pacote via rabbitMQ para envio de email ao recuperar senha e confirmar conta. Opcional, pois é necessário que esteja com o envio de email ativo.")

Rel(HorusecCore, HorusecAuth, "Requisição enviada via GRPC para validar autenticidade da chamada HTTP recebida do manager.")
Rel(HorusecCore, HorusecMessages, "Pacote via rabbitMQ para envio de email ao usuário ser convidado para workspace ou repositório. Opcional, pois é necessário que esteja com o envio de email ativo.")

Rel(HorusecVulnerability, HorusecAuth, "Requisição enviada via GRPC para validar autenticidade da chamada HTTP recebida do manager.")
Rel(HorusecVulnerability, HorusecAnalytic, "Pacote via rabbitMQ para envio de alterações nos dados das vulnerabilidades.")

Rel(HorusecWebhook, externalAPP, "Requisição enviada via HTTP através do webhook configurado no horusec para alguma aplicação externa. Opcional, pois caso não tenha nenhum webhook configurado não irá ocorrer.")

Rel(HorusecAPI, HorusecAuth, "Requisição enviada via GRPC para validar autenticidade da chamada HTTP recebida do manager.")

Rel(horusecCLI, HorusecAPI, "Envia os dados das vulnerabilidades encontradas para o Horusec API.")

@enduml
