@startuml

!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Deployment.puml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Dynamic.puml
' uncomment the following line and comment the first to use locally
' !include C4_Container.puml

' LAYOUT_TOP_DOWN()
' LAYOUT_AS_SKETCH()

LAYOUT_WITH_LEGEND()

Person(user, "Desenvolvedor / Esteira CICD", "Qualquer usuário que interage diretamente com o código fonte do software.")

System_Boundary(horusecCLI, "Horusec-CLI") {
    Container(horusecCLIPhase1, "Horusec-CLI Phase 1", "Step", "Realiza Verificações de entrada de dados")
    Container(horusecCLIPhase2, "Horusec-CLI Phase 2", "Step", "Inicía análise")
    Container(horusecCLIPhase3, "Horusec-CLI Phase 3", "Step", "Inicía análise")
    Container(horusecCLIPhase4, "Horusec-CLI Phase 4", "Step", "Inicía análise")
    ' ContainerDb(database, "Database", "SQL Database", "Stores user registraion information, hased auth credentials, access logs, etc.")
}


Rel(user, horusecCLIPhase1, "horusec start", "command")
Rel(horusecCLIPhase1, horusecCLIPhase2, "Logic", "internal")
Rel(horusecCLIPhase2, horusecCLIPhase3, "Logic", "internal")
Rel(horusecCLIPhase3, horusecCLIPhase4, "Logic", "internal")
' Rel(user, spa, "Uses", "HTTPS")
' Rel(user, mobile_app, "Uses")

' Rel_Neighbor(web_app, spa, "Delivers")
' Rel(spa, backend_api, "Uses", "async, JSON/HTTPS")
' Rel(mobile_app, backend_api, "Uses", "async, JSON/HTTPS")
' Rel_Back_Neighbor(database, backend_api, "Reads from and writes to", "sync, JDBC")

@enduml
