@startuml horusec-operator-c2
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Deployment.puml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Dynamic.puml

LAYOUT_WITH_LEGEND()

Person(user, "SRE/DevSecOps/DevOps", "Pessoa que queira instalar ou realizar a manutenção do Horusec-Platform em um cluster Kubernetes.")

System_Boundary(horusecOperator, "Horusec-Operator") {
  System(HorusecOperatorPhase0, "Usuário instala a CRD do Horusec em seu cluster.")
  System(HorusecOperatorPhase1, "O horusec-operator é notificado pelo kubernetes, que aplica o estado de configurações para atingir o estado desejado.")
}

System_Ext(Kubernetes, "Kubernetes", "Sistema de orquestração de contêineres")

Rel(user, HorusecOperatorPhase0, "")
Rel(HorusecOperatorPhase0, Kubernetes, "")
Rel(Kubernetes, HorusecOperatorPhase1, "")


@enduml
