@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml

LAYOUT_WITH_LEGEND()

Person(user, "Desenvolvedor/QA/AppSec/Gestor/Supervisor/CTO", "Qualquer pessoa que deseja realizar a gestão de vulnerabilidades do seu projeto.")
System(horusecPlatform, "Horusec Platform (opcional)", "Ferramenta WEB para gerenciar e visualizar as vulnerabilidades encontradas pela CLI.")

Rel(user, horusecPlatform, "Realiza interação através da interface gráfica do Horusec")

Rel(horusecPlatform, user, "Retorna dados para usuário realizar o gerenciamento dos seus workspaces e repositórios")

@enduml
